import type { ReactNode } from "react";
import { ArrowLeft, ExternalLink, FileText, ShieldCheck, Sunrise } from "lucide-react";
import SiteFooter from "@/components/SiteFooter";

/**
 * 老東家晨光日出設計提醒：法律與官方資訊頁保留足夠留白與深靛文字，杏橘只標示版本與行動；讓重要條文像清晨航圖一樣清楚可讀。
 */

const basePath = import.meta.env.BASE_URL;

function LegalShell({ eyebrow, title, intro, icon, children }: { eyebrow: string; title: string; intro: string; icon: "privacy" | "terms" | "official"; children: ReactNode }) {
  const Icon = icon === "privacy" ? ShieldCheck : icon === "terms" ? FileText : Sunrise;
  return <div className="min-h-screen bg-[#f7fbfb] text-[#172846]"><header className="sticky top-0 z-30 border-b border-[#bfd6df] bg-[#f8fcfc]/90 backdrop-blur-xl"><div className="container flex h-[72px] items-center justify-between"><a href={basePath} className="inline-flex items-center gap-2 text-sm font-bold text-[#36536c] transition hover:text-[#e15b32]"><ArrowLeft size={18}/> 回到老東家</a><a href={basePath} className="flex items-center gap-2"><img className="size-10 rounded-[14px] object-cover ring-1 ring-[#e4ab52]/45" src={`${basePath}media/odj-sunrise-icon.png`} alt="老東家日出圖示"/><span className="font-display text-lg font-black tracking-[0.08em]">老東家</span></a></div></header><main><section className="border-b border-[#bfd6df] bg-[#edf7f8]"><div className="container grid gap-8 py-16 sm:py-20 md:grid-cols-[1fr_auto] md:items-end"><div><p className="font-mono text-[11px] tracking-[0.18em] text-[#d85c36]">{eyebrow}</p><h1 className="font-display mt-4 text-4xl font-black tracking-[-0.04em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#466279]">{intro}</p></div><div className="grid size-16 place-items-center rounded-[24px] border border-[#eab354]/55 bg-[#fff9ed] text-[#e15b32] shadow-sm"><Icon size={29}/></div></div></section><section className="container py-12 sm:py-16"><div className="mx-auto max-w-3xl">{children}</div></section></main><SiteFooter /></div>;
}

function Notice() {
  return <div className="mb-10 rounded-[22px] border border-[#f0b26a] bg-[#fff5e8] p-5 text-sm leading-7 text-[#7b4a32]"><p className="font-bold">原型網站說明</p><p className="mt-1">老東家目前是公開互動原型。本站已開放 Google 登入、會員工作台與提案草稿儲存，讓使用者體驗帳號與創作流程；尚未開放付款、訂單、配送、真實提案審核或客服案件收件。正式營運前，將依實際營運主體、合作服務與資料流程更新本頁內容。</p></div>;
}

function LegalSection({ number, title, children }: { number: string; title: string; children: ReactNode }) {
  return <section className="border-t border-[#c9dee5] py-8 first:border-t-0 first:pt-0"><div className="flex gap-5"><p className="font-mono text-sm text-[#e15b32]">{number}</p><div className="min-w-0 flex-1"><h2 className="font-display text-2xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-8 text-[#466279]">{children}</div></div></div></section>;
}

export function PrivacyPage() {
  return <LegalShell eyebrow="PRIVACY NOTE / 2026.08.17" title="隱私權政策" intro="這份政策說明老東家網站目前如何處理瀏覽、登入、會員工作台與提案草稿資料。請先閱讀原型網站說明，再決定是否持續使用本站。" icon="privacy"><Notice /><LegalSection number="01" title="適用範圍與版本"><p>本政策適用於 <b>larrylai777.github.io/ODJ-Sponsor/</b> 所呈現的老東家 ODJ Sponsor 網站、會員工作台與本頁所連結的官方資訊。本版本自 2026 年 8 月 17 日起適用；若日後啟用付款、提案審核、配送或客服功能，會在收集資料前以更新版本說明新的處理方式。</p></LegalSection><LegalSection number="02" title="目前可能處理的資料"><p>當你選擇 Google 登入時，Firebase Authentication 會依 Google 同意畫面與 Firebase 服務設定，向本站提供登入識別所需的資料，例如 Firebase 使用者識別碼、顯示名稱、電子郵件地址與個人頭像網址。本站會在 Firebase Cloud Firestore 保留必要的會員識別欄位；當你建立提案草稿或使用收藏功能時，本站也會儲存與帳號相連的草稿或收藏資料。</p><p>會員資料與收藏資料的資料庫規則僅允許相同登入帳號讀寫；提案草稿僅限作者本人建立、讀取、修改或刪除，且不可在更新時變更作者身分。支持紀錄目前不由用戶端建立，正式贊助尚未開放。</p><p>為維護網站運作、理解頁面使用情形與偵錯，網站託管或分析服務可能產生裝置與瀏覽資料，例如瀏覽器類型、作業系統、語言、造訪頁面、來源頁、使用時間、概略網路位置與技術識別資訊。本站亦載入 Google Fonts 字型資源，並以 GitHub Pages 提供靜態頁面；各服務供應商可能依其自身政策處理技術連線或存取紀錄。</p></LegalSection><LegalSection number="03" title="資料使用目的"><p>登入與會員工作台資料僅用於維持 Google 登入工作階段、顯示登入帳號、呈現你自己的收藏、支持紀錄與提案草稿，以及安全登出。技術資料僅用於維持網站可用性、資安與除錯、衡量公開頁面的使用趨勢，以及改善內容與介面。本站目前不販售訪客個資，也不以本原型網站資料進行個別化廣告投放或高影響決策。</p></LegalSection><LegalSection number="04" title="資料分享與跨境傳輸"><p>為提供登入與資料保存服務，資料可能由 Google、Firebase Authentication、Cloud Firestore、GitHub Pages、字型、分析或資安服務供應商依其服務所在地處理。除非法律要求、為防止詐欺或資安事件所必需，或你在正式功能開放後另行明確同意，老東家不會將你的資料出售或任意提供給非必要第三方。</p></LegalSection><LegalSection number="05" title="保存期間與安全"><p>Google 登入及會員工作台資料會依相關服務設定與達成原型功能目的所需期間保存。你可以隨時登出；如需提出原型資料相關的查詢或刪除請求，請以 Google 登入同意畫面公開的支援信箱 <b>eric40311toby@gmail.com</b> 聯絡。正式營運前，老東家會依實際資料類別、保存期限、權限控管、委外廠商與事件通報流程補充具體資訊。</p></LegalSection><LegalSection number="06" title="政策更新與法規參考"><p>我們可能在功能、合作服務或法令要求改變時更新本政策，並會在本頁調整版本日期。台灣個人資料保護法的官方文本可於<a className="ml-1 font-semibold text-[#d9522d] underline underline-offset-4" href="https://law.moj.gov.tw/LawClass/LawAll.aspx?PCode=I0050021" target="_blank" rel="noreferrer">全國法規資料庫<ExternalLink className="ml-1 inline" size={13}/></a>查閱。</p></LegalSection></LegalShell>;
}

export function TermsPage() {
  return <LegalShell eyebrow="SITE TERMS / 2026.08.17" title="網站使用條款" intro="這些條款說明使用老東家網站時的基本規則，以及目前互動原型與正式募資服務之間的界線。" icon="terms"><Notice /><LegalSection number="01" title="接受條款"><p>你瀏覽、Google 登入或使用本站時，即表示同意遵守本使用條款及隱私權政策。若你不同意其中任一內容，請停止使用本站。本條款僅規範目前公開網站的使用；未來正式功能、創作者提案審核、贊助交易、付款、物流或退款，將另以適用的服務條款、專案條款與付款說明規範。</p></LegalSection><LegalSection number="02" title="原型性質與非交易聲明"><p>老東家目前是產品概念與互動流程原型。Google 登入、會員工作台與提案草稿僅用於展示帳號識別及創作資料保存流程，不代表已開放正式提案審核、付款或訂單服務。頁面上顯示的作品、金額、支持人數、時程、回饋項目、庫存、進度與通知均為展示用途；它們不構成募資邀約、金融商品、投資建議、付款要約、訂單確認、出貨承諾或消費契約。本站目前不會向你收款、建立訂單或受理真實贊助。</p></LegalSection><LegalSection number="03" title="允許與禁止的使用方式"><p>你可以為了解老東家的產品概念而合理瀏覽、登入、分享公開連結或建立自己的提案草稿。你不得以任何方式破壞、測試或繞過網站安全機制；不得大量擷取或重製內容以建立競爭性服務；不得冒用老東家、創作者或其他第三方名義；亦不得利用本站傳輸違法、侵權、具惡意程式或可能損害他人權益的內容。</p></LegalSection><LegalSection number="04" title="內容與智慧財產"><p>本站的介面、文字、視覺設計、商標、名稱、程式碼與素材，除另有標示外，受適用的智慧財產權保護。展示作品及其相關設定仍屬原權利人或其授權人所有。未經權利人事前書面同意，你不得將上述內容用於商業重製、散布、改作、公開傳輸或使人誤認為與老東家有合作關係。</p></LegalSection><LegalSection number="05" title="外部連結與條款變更"><p>本站可能連結至 Google、Firebase、GitHub、Facebook、字型服務或其他第三方網站。這些網站由各自的經營者管理，其內容、可用性、隱私實務與服務條款不在老東家的控制範圍內。老東家可在不另行通知的情況下調整、暫停或終止原型功能；若有正式營運主體、交易、資料處理、退款或消費爭議處理安排，將在上線前明確公告。</p></LegalSection></LegalShell>;
}

export function OfficialPage() {
  return <LegalShell eyebrow="OFFICIAL NOTE / 2026.08.17" title="關於老東家" intro="老東家 ODJ Sponsor 正在探索：如何讓華文小說與收藏型周邊，在被理解後獲得支持，並被有節奏地製作與送達。" icon="official"><Notice /><LegalSection number="01" title="平台定位"><p>老東家是以華文小說、實體書、電子書、繪本、輕小說及其衍生周邊為核心的群眾支持平台構想。平台希望讓創作者、編輯、製作夥伴與讀者，在故事、規格、時程與回饋都被清楚說明的條件下同行。</p></LegalSection><LegalSection number="02" title="目前官方狀態"><p>網站名稱為「老東家 ODJ Sponsor」，目前公開網址為本 GitHub Pages 原型。網站已啟用 Google 登入、個人會員工作台與僅屬於帳號本人的提案草稿；尚未開放真實贊助、付款、訂單、物流、正式提案審核或客服案件。頁面所呈現的專案、數字與方案仍僅用於展示資訊架構與使用流程。</p></LegalSection><LegalSection number="03" title="正式上線前將公告的資訊"><p>在開始處理真實交易或更完整的個資前，網站將補充並公開營運主體名稱、登記資訊、有效聯絡方式、客服服務時間、資料保護窗口、付款服務供應商、退款與取消規則、配送範圍、消費者權益資訊、創作者審核與專案履約機制，以及正式版本的隱私權政策與服務條款。</p></LegalSection><LegalSection number="04" title="官方連結"><p>目前公開的老東家管道包括本網站、使用者指定的<a className="ml-1 font-semibold text-[#d9522d] underline underline-offset-4" href="https://www.facebook.com/share/19TwFNqfoG/?mibextid=wwXIfr" target="_blank" rel="noreferrer">Facebook 社群<ExternalLink className="ml-1 inline" size={13}/></a>與<a className="ml-1 font-semibold text-[#d9522d] underline underline-offset-4" href="https://github.com/larrylai777/ODJ-Sponsor" target="_blank" rel="noreferrer">ODJ Sponsor GitHub 儲存庫<ExternalLink className="ml-1 inline" size={13}/></a>。如有其他社群帳號、電子郵件、付款頁面或活動頁面，必須在本頁正式公告後才視為老東家的官方管道。</p></LegalSection></LegalShell>;
}
