import { useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, Check, Heart, PackageCheck, ShieldCheck, Sunrise, X } from "lucide-react";
import SiteFooter from "@/components/SiteFooter";

/**
 * 老東家晨光日出設計提醒：專案頁像一張向海平線展開的航圖；深靛承接可信資訊，曙光杏橘只用於行動與進度，日出 Logo 固定使用 40px 正方形圓角徽章。
 */

const rewardOptions = [
  { id: "digital", name: "晨讀支持", price: "NT$ 280", detail: "電子書 + 募資限定晨光桌布", stock: "不限量" },
  { id: "book", name: "首航精裝版", price: "NT$ 780", detail: "精裝本、暖金藏書票、作者後記", stock: "剩 128 份" },
  { id: "collector", name: "潮汐曙光典藏組", price: "NT$ 1,680", detail: "精裝本 + 雙面壓克力立牌 + 3 張角色卡 + 典藏書盒", stock: "剩 42 份" },
];

const asset = (name: string) => `${import.meta.env.BASE_URL}media/${name}`;
const homePath = import.meta.env.BASE_URL;
const projectImage = asset("odj-dawn-project.jpg");

export default function Project() {
  const [selected, setSelected] = useState("book");
  const [modalOpen, setModalOpen] = useState(false);
  const current = rewardOptions.find((item) => item.id === selected) ?? rewardOptions[1];

  const continueToSponsor = () => { setModalOpen(false); toast("已保留方案（示意）", { description: `已選擇「${current.name}」。正式版本將在此銜接金流與寄送資訊。` }); };

  return <div className="min-h-screen bg-[#f7fbfb] text-[#172846]">
    <header className="sticky top-0 z-30 border-b border-[#bfd6df] bg-[#f8fcfc]/90 backdrop-blur-xl"><div className="container flex h-[72px] items-center justify-between"><a href={homePath} className="inline-flex items-center gap-2 text-sm font-bold text-[#36536c] transition hover:text-[#e15b32]"><ArrowLeft size={18}/> 回到今日啟航</a><a href={homePath} className="flex items-center gap-2"><img className="size-10 shrink-0 rounded-[14px] object-cover object-center shadow-sm ring-1 ring-[#e4ab52]/45" src={asset("odj-sunrise-icon.png")} alt="老東家日出圖示"/><span className="font-display text-lg font-black tracking-[0.08em] text-[#172846]">老東家</span></a></div></header>
    <main className="container py-9 sm:py-14"><div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_400px] lg:gap-14"><div>
      <div className="mb-6 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs"><span className="sun-stamp border border-[#7facc0] bg-[#172846] px-3 py-1.5 font-semibold tracking-[0.12em] text-[#fffaf3]">今晨精選</span><span className="font-bold text-[#e15b32]">奇幻小說</span><span className="text-[#698396]">邊城製本所</span></div>
      <h1 className="font-display text-4xl font-black leading-[1.22] tracking-[-0.04em] sm:text-6xl">月海檔案：<br/><span className="text-[#f36b3b]">潮汐退去之後</span></h1>
      <p className="mt-6 max-w-2xl text-lg leading-9 text-[#476279]">當海水每夜退去，城市底下便露出一座被遺忘的月亮。這是一本關於失物、潮聲與重返故鄉的長篇奇幻小說；也將是我們想好好做成的第一套特裝書。</p>
      <div className="relative mt-10 overflow-hidden rounded-[30px] border border-[#c5dce4] bg-[#dceaf0] dawn-shadow"><img src={projectImage} alt="月海檔案特裝書與周邊在清晨光線中的展示" className="aspect-[16/8] w-full object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(23,40,70,.1),transparent_45%)]"/><div className="absolute bottom-5 left-5 flex items-center gap-2 rounded-full border border-white/50 bg-[#172846]/90 px-3 py-2 font-mono text-[10px] tracking-[0.14em] text-[#ffe0a2]"><Sunrise size={14}/> TIDE AT FIRST LIGHT</div></div>
      <div className="mt-12 grid gap-10 border-t border-[#c9dee5] pt-10 sm:grid-cols-2"><div><h2 className="font-display text-3xl font-bold">這次想做的，<br/>不只是一冊書</h2><p className="mt-4 leading-8 text-[#506c81]">特裝版會採精裝書衣、前後蝴蝶頁與暖金藏書票。典藏組另外收錄兩位主角的雙面壓克力立牌、角色卡與書盒；每一項回饋都會在打樣完成後於進度頁公開確認。</p></div><div className="border-l border-[#c9dee5] pl-0 sm:pl-8"><h3 className="font-display text-2xl font-bold">我們的航程</h3><ul className="mt-5 space-y-4 text-sm text-[#38546c]"><li className="flex gap-3"><Check className="mt-0.5 shrink-0 text-[#f36b3b]" size={17}/><span><b>2026/08</b>　完成內容校對與書封提案</span></li><li className="flex gap-3"><Check className="mt-0.5 shrink-0 text-[#f36b3b]" size={17}/><span><b>2026/09</b>　完成印刷、周邊打樣確認</span></li><li className="flex gap-3"><PackageCheck className="mt-0.5 shrink-0 text-[#f36b3b]" size={17}/><span><b>2026/11</b>　依贊助方案分批寄出</span></li></ul></div></div>
      <div className="mt-14 rounded-[26px] border border-[#c9dee5] bg-[#edf6f7] p-7"><p className="font-mono text-[11px] tracking-[0.16em] text-[#e15b32]">DAWN LOG · 2026.08.12</p><h2 className="font-display mt-3 text-3xl font-bold">我們把月光，放進第一道晨光裡</h2><p className="mt-4 max-w-2xl leading-8 text-[#506c81]">首輪樣紙已完成測試，內襯選用偏霧面的珍珠紙，讓月海的藍色在不同角度有更安靜的反光。下一篇更新會公開立牌的正式線稿。</p></div>
    </div>
    <aside className="lg:sticky lg:top-24 lg:h-fit"><div className="overflow-hidden rounded-[28px] border border-[#bcd5df] bg-white/88 p-6 dawn-shadow"><div className="flex items-start justify-between border-b border-dashed border-[#c9dee5] pb-4"><div><p className="font-mono text-[10px] tracking-[0.14em] text-[#6a879a]">DAWN COURSE / FUNDING</p><p className="font-mono mt-1 text-[10px] text-[#e15b32]">NO. ODJ-MH-0826</p></div><span className="sun-stamp border-2 border-[#f36b3b] px-2 py-1 font-mono text-[10px] font-bold tracking-[0.13em] text-[#d9522d]">已啟航</span></div><div className="mt-5 flex items-end justify-between"><div><p className="font-mono text-xs text-[#6a879a]">本期同行總額</p><p className="font-mono mt-2 text-3xl font-medium text-[#172846]">NT$ 438,560</p></div><p className="font-mono text-sm text-[#e15b32]">146%</p></div><div className="mt-5 h-[5px] overflow-hidden rounded-full bg-[#dceaf0]"><div className="h-full w-full rounded-full bg-[#f36b3b]"/></div><div className="mt-3 flex justify-between font-mono text-[10px] text-[#6a879a]"><span>目標 NT$ 300,000</span><span>期限 剩 16 天</span></div><div className="mt-6 grid grid-cols-2 border-y border-dashed border-[#c9dee5] py-4"><div><p className="font-mono text-lg">642</p><p className="mt-1 text-[10px] tracking-[0.08em] text-[#668296]">一起等候的人</p></div><div className="border-l border-[#d7e8ed] pl-4"><p className="font-mono text-lg">11.28</p><p className="mt-1 text-[10px] tracking-[0.08em] text-[#668296]">預計抵達日期</p></div></div>
      <div className="mt-7"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold tracking-[0.1em] text-[#25435c]">選一份晨光支持</p><p className="font-mono text-[10px] text-[#718c9d]">SAIL / 03</p></div><div className="space-y-2">{rewardOptions.map((option, index) => <button key={option.id} onClick={() => setSelected(option.id)} className={`w-full rounded-[18px] border p-3 text-left transition ${selected === option.id ? "border-[#f36b3b] bg-[#fff2e8]" : "border-[#d2e3e8] hover:border-[#86aebe] hover:bg-[#f6fbfc]"}`}><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><span className="font-mono text-[10px] text-[#e15b32]">0{index + 1}</span><div><p className="text-sm font-bold">{option.name}</p><p className="mt-1 text-xs leading-5 text-[#688398]">{option.detail}</p></div></div><p className="font-mono shrink-0 text-sm">{option.price}</p></div><p className={`mt-2 font-mono text-[10px] ${option.stock.includes("剩") ? "text-[#e15b32]" : "text-[#718c9d]"}`}>{option.stock}</p></button>)}</div></div>
      <button onClick={() => setModalOpen(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#f36b3b] py-4 text-sm font-bold text-[#fffaf3] transition hover:-translate-y-0.5 hover:bg-[#d9522d] active:scale-[0.97]">陪「{current.name}」啟航<Heart size={16}/></button><div className="mt-5 flex gap-2 border-t border-[#dceaf0] pt-4 text-[11px] leading-5 text-[#698396]"><ShieldCheck className="mt-0.5 shrink-0 text-[#f36b3b]" size={16}/>此為互動原型，不會收取實際款項。正式版本可在此呈現退款、金流與寄送條款。</div></div></aside></div></main>
    <SiteFooter />
    {modalOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#172846]/55 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-[26px] border border-white/60 bg-[#f8fcfc] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="font-mono text-xs text-[#e15b32]">SPONSOR CHECKOUT · DEMO</p><h2 className="font-display mt-2 text-3xl font-bold">確認這段航程</h2></div><button onClick={() => setModalOpen(false)} className="rounded-2xl p-1 text-[#38546c]" aria-label="關閉"><X size={20}/></button></div><div className="mt-6 border-y border-[#d2e3e8] py-4"><p className="font-semibold">{current.name}</p><p className="mt-1 text-sm text-[#688398]">{current.detail}</p><p className="font-mono mt-3 text-xl">{current.price}</p></div><p className="mt-5 text-sm leading-7 text-[#506c81]">這一步在正式產品中會串接贊助者資料、配送方式與受管控的付款流程。</p><button onClick={continueToSponsor} className="mt-6 w-full rounded-2xl bg-[#f36b3b] py-3.5 text-sm font-bold text-[#fffaf3] transition hover:bg-[#d9522d] active:scale-[0.97]">完成方案選擇（示意）</button></div></div>}
  </div>;
}
